/*
 * SPDX-License-Identifier: BSD-2-Clause
 *
 *​ Copyright (c) 2025 The FreeBSD Foundation
 *​
 *​ Portions of this software were developed by
 * Tuukka Pasanen <tuukka.pasanen@ilmi.fi> under sponsorship from
 * the FreeBSD Foundation
 */

#include <stdlib.h>
#include <string.h>
#include "serialize.h"


#ifndef CLI__SBOMTOOL__CYCLONEX__COMPONENT_H
#define CLI__SBOMTOOL__CYCLONEX__COMPONENT_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum cyclonedx_component_type_ {
    CYCLONEX_COMPONENT_APPLICATION = 1,
    CYCLONEX_COMPONENT_FRAMEWORK,
    CYCLONEX_COMPONENT_LIBRARY,
    CYCLONEX_COMPONENT_CONTAINER,
    CYCLONEX_COMPONENT_PLATFORM,
    CYCLONEX_COMPONENT_OPERATING_SYSTEM,
    CYCLONEX_COMPONENT_DEVICE,
    CYCLONEX_COMPONENT_DEVICE_DRIVER,
    CYCLONEX_COMPONENT_FIRMWARE,
    CYCLONEX_COMPONENT_FILE,
    CYCLONEX_COMPONENT_MACHINE_LEARNING_MODEL,
    CYCLONEX_COMPONENT_DATA,
    CYCLONEX_COMPONENT_CRYPTOGRAHIC_ASSET
} cyclonedx_component_type_t;

typedef enum cyclonedx_component_external_ {
    CYCLONEX_COMPONENT_EXT_VCS = 1,
    CYCLONEX_COMPONENT_EXT_ISSUE_TRACKER,
    CYCLONEX_COMPONENT_EXT_WEBSITE,
    CYCLONEX_COMPONENT_EXT_ADVISORIES,
    CYCLONEX_COMPONENT_EXT_BOM,
    CYCLONEX_COMPONENT_EXT_MAILING_LIST,
    CYCLONEX_COMPONENT_EXT_SOCIAL,
    CYCLONEX_COMPONENT_EXT_CHAT,
    CYCLONEX_COMPONENT_EXT_DOCUMENTATION,
    CYCLONEX_COMPONENT_EXT_SUPPORT,
    CYCLONEX_COMPONENT_EXT_SOURCE_DISTRIBUTION,
    CYCLONEX_COMPONENT_EXT_DISTRIBUTION,
    CYCLONEX_COMPONENT_EXT_DISTRIBUTION_INTAKE,
    CYCLONEX_COMPONENT_EXT_DISTRIBUTION_LICENSE,
    CYCLONEX_COMPONENT_EXT_BUILD_META,
    CYCLONEX_COMPONENT_EXT_BUILD_SYSTEM,
    CYCLONEX_COMPONENT_EXT_RELEASE_NOTES,
    CYCLONEX_COMPONENT_EXT_SECURITY_CONTACT,
    CYCLONEX_COMPONENT_EXT_MODEL_CARD,
    CYCLONEX_COMPONENT_EXT_LOG,
    CYCLONEX_COMPONENT_EXT_CONFIGURATION,
    CYCLONEX_COMPONENT_EXT_EVIDENCE,
    CYCLONEX_COMPONENT_EXT_FORMULATION,
    CYCLONEX_COMPONENT_EXT_ATTESTATION,
    CYCLONEX_COMPONENT_EXT_THREAD_MODEL,
    CYCLONEX_COMPONENT_EXT_ADVESARY_MODEL,
    CYCLONEX_COMPONENT_EXT_RISK_ASSESSMENT,
    CYCLONEX_COMPONENT_EXT_VULNERABILITY_ASSERTION,
    CYCLONEX_COMPONENT_EXT_EXPLOITABILITY_STATEMENT,
    CYCLONEX_COMPONENT_EXT_PENTEST_REPORT,
    CYCLONEX_COMPONENT_EXT_STATIC_ANALYSIS_REPORT,
    CYCLONEX_COMPONENT_EXT_DYNAMIC_ANALYSIS_REPORT,
    CYCLONEX_COMPONENT_EXT_RUNTIME_ANALYSIS_REPORT,
    CYCLONEX_COMPONENT_EXT_COMPONENT_ANALYSIS_REPORT,
    CYCLONEX_COMPONENT_EXT_MATURITY_REPORT,
    CYCLONEX_COMPONENT_EXT_CERTIFICATION_REPORT,
    CYCLONEX_COMPONENT_EXT_CODIFIED_INDRASTRUCTURE,
    CYCLONEX_COMPONENT_EXT_QUALITY_METRICS,
    CYCLONEX_COMPONENT_EXT_POAM,
    CYCLONEX_COMPONENT_EXT_DIGITAL_SIGNATURE,
    CYCLONEX_COMPONENT_EXT_RFC_9116,
    CYCLONEX_COMPONENT_EXT_PATENT,
    CYCLONEX_COMPONENT_EXT_PATENT_FAMILY,
    CYCLONEX_COMPONENT_EXT_PATENT_ASSERTION,
    CYCLONEX_COMPONENT_EXT_CITATION,
    CYCLONEX_COMPONENT_EXT_OTHER
} cyclonedx_component_ext_t;


pkgconfcli_serialize_value_t *
sbomtool_cyclonedx_component_new(pkgconf_client_t *client, cyclonedx_component_type_t type, const char *name, const char *version, bool additional);

bool
sbomtool_cyclondex_component_add_license(pkgconf_client_t *client, pkgconfcli_serialize_array_t *licenses, const char *id);

bool
sbomtool_cyclondex_component_add_externalReference(pkgconf_client_t *client, pkgconfcli_serialize_array_t *ext_ref, cyclonedx_component_ext_t type, const char *ref);

bool
sbomtool_cyclondex_component_add_author(pkgconf_client_t *client, pkgconfcli_serialize_array_t *maintainers, const char *name, const char *email, const char *phone);


void
sbomtool_cyclondex_component_add_package(pkgconf_client_t *client, pkgconf_pkg_t *pkg, void *ptr, unsigned int iter_flags);



#ifdef __cplusplus
}
#endif

#endif
